[solution]
name = "my-team-solution-v1"      # Solution name
# Track: moe | dsa_sparse_attention | dsa_topk_indexer | gdn_decode | gdn_prefill
definition = "moe"          
author = "team-name"              # Team/author name

[build]
language = "python"               # triton | cuda
entry_point = "kernel.py::kernel"            # Kernel function name
destination_passing_style = false